const LOADING_TRUE = "LOADING_TRUE";
const LOADING_FALSE = "LOADING_FALSE";
// Add Mobile
const ADD_MOBILE_SUCCESS = "ADD_MOBILE_SUCCESS";
const ADD_MOBILE_FAILURE = "ADD_MOBILE_FAILURE";
// Fetch Mobile List
const FETCH_MOBILE_LIST_SUCCESS = "FETCH_MOBILE_LIST_SUCCESS";
const FETCH_MOBILE_LIST_FAILURE = "FETCH_MOBILE_LIST_FAILURE";
// Auth:
// signup
const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
// signin
const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
// signout
const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

export {
  LOADING_TRUE,
  LOADING_FALSE,
  // Mobile info:
  ADD_MOBILE_SUCCESS,
  ADD_MOBILE_FAILURE,
  FETCH_MOBILE_LIST_SUCCESS,
  FETCH_MOBILE_LIST_FAILURE,
  // Auth:
  SIGN_UP_SUCCESS,
  SIGN_UP_FAILURE,
  SIGN_IN_SUCCESS,
  SIGN_IN_FAILURE,
  SIGN_OUT_SUCCESS,
};
